name: Testing github Actions
run-name: Test run for python

on: [pull_request,push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python main.py